version: "2"
services:
  zipkin:
    image: openzipkin/zipkin:2.23
    container_name: zipkin
    environment:
      - TZ=Asia/Shanghai
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=192.168.88.116:9200
    ports:
      - 9411:9411
