version: "2"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=change-it
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
